// The program will provide 3 random sentence of Goldilocks, the three little pigs and The Red Riging Hood.

const redRidingHood = ["Once upon a time, there lived a little girl called Little Red Riding Hood.", 
"She wore a beautiful red cape that her grandma had made for her.", 
"One day, her mother said, 'Come here Little Red Riding Hood. Your grandma is not very well. I would like you to take this bread and cheese to her but remember to stay on the path.'", 
"Little Red Riding Hood set off to her grandma’s house. She lived on the other side of a forest.", 
"As Little Red Riding Hood was going through the wood, she met a wolf.", 
"He was waiting for her to get closer and closer and closer and then…. he jumped out from behind a tree!", 
"The wolf asked. 'Where are you going to?' Little Red Riding Hood said, 'I am going to see my grandma because she is not very well.'", 
"The wolf gazed at her and said, 'See these pretty flowers? Why not pick some, I am sure your grandma would love them.'", 
"'What a good idea,' said Little Red Riding Hood, and she skipped from the path to look for flowers for her grandma.", 
"Then the wolf ran to grandma’s house and knocked on the door. -Knock, knock, knock!- 'Who is there?' asked grandma. 'Little Red Riding Hood', replied the wolf.", 
"Grandma whispered, 'Come in, I am too ill to come to the door.' The wolf let himself in.", 
"Poor granny did not have time to say another word, before the greedy wolf gobbled her up!", 
"He put on her nightgown and nightcap. He jumped into granny’s bed and pulled the covers over his nose.", 
"Unaware of what happened, Little Red Riding Hood came joyfully to her granny’s house and knocked on the door: -Knock! Knock!-", 
"Behind the door, a hoarse voice answered: 'Is it you, Little Red Riding Hood? Come in! Come in!'.", 
"Now Little Red Riding Hood realised that her granny may feel very ill and, feeling a little worried, stepped in the house.", 
"Little Red Riding Hood was very surprised when she saw her grandmother.", 
"'Granny, what happened to you? Why have you got those large ears?' the girl asked amazed. 'All the better to hear you with', the wolf answered.", 
"'And why have you got those big eyes?', continued Little Red Riding Hood. 'To see you better!' said the wolf.", 
"'And what about those big sharp teeth?', carried on Little Red Riding Hood. 'All the better to eat you', bellowed the wolf and with a jump and a gulp he gobbled Little Red Riding Hood up.", 
"'Yummy!', he said, patting his large tummy.", 
"But, the wolf didn’t know that a forest ranger was just passing by. He had listened to Little Red Riding Hood talking to the wolf.", 
"At first he himself thought that granny had quite a coarse voice but soon he realised that something odd was happening and he rushed into the house exactly when the wolf was patting his tummy.", 
"'You greedy wolf! Spit out what you swallowed or you’ll never see another day!', the ranger shouted.", 
"Surprised and frightened, the wolf immediately spat Little Red Riding Hood and her grandma out of his belly and ran out of the house.", 
"Little Red Riding Hood and her granny thanked the brave forest ranger for rescuing them.", 
"Granny even started feeling better after eating some of the lovely food Little Red Riding Hood brought.", 
"There was no end to their joy. ( and they lived happily ever after)."]

const threePigs = ["Once upon a time, there were three little pigs.", 
" The pigs lived in a small house with their mum.", 
"One day, their mum sent them off to build houses of their own.", 
"As they walked down the road, the first little pig met a farmer pulling a cart of straw.", 
" It looked very warm - just right for building a house. He asked if he could have some", 
"The farmer agreed and the first little pig began to build his straw house.", 
" A little way down the road, the second little pig saw a woodcutter with a cart of sticks.", 
"They looked thick and long - just right for building a house. He asked if he could have some.", 
"The woodcutter agreed and the second little pig began to build his wooden house.", 
" The third little pig trotted down the road. After a short time, he met a builder pushing a wheelbarrow full of bricks.", 
"The third little pig thought to himself, 'How strong those bricks look! I think they would make an excellent house.'", 
"So, the third little pig asked the builder for some of his bricks and he began to build a house that was stronger and bigger than the others.", 
"Soon, all three little pigs had a house of their own and they were all very happy.", 
"Then,one day, a big bad wolf came walking along the road.", 
"He saw the first little pig in his straw house. With an evil glint in his eye, he knocked on the first little pig’s door.", 
"'Little pig, little pig, let me come in!' he said.", 
"'Not by the hair on my chinny, chin, chin! I will not let you in!' cried the frightened little pig.", 
"'Then I will huff and I will puff, and I will BLOW your house down!' growled the wolf.", 
"The wolf huffed and he puffed and he blew the straw house down.", 
"The first little pig ran all the way to his brother’s wooden house.", 
"The wolf was soon at the house made of sticks. He knocked on the door.", 
"'Little pigs, little pigs, let me come in!' he snarled.", 
"'Not by the hairs on our chinny, chin, chins! We will not let you in!' cried the frightened little pigs.", 
"'Then I’ll huff and I’ll puff and I’ll BLOW your house down!' growled the wolf.", 
"The wolf huffed and he puffed and he blew the house down.", 
"The two little pigs ran as fast as they could all the way to their brother’s brick house.",
"The wolf was soon at the brick house. He knocked on the door.", 
"'Little pigs, little pigs, let me come in!' he growled.", 
"'Not by the hairs on our chinny, chin, chins! We will not let you in!' squeaked the little pigs.", 
"'Then I’ll huff and I’ll puff and I’ll BLOW your house down!' roared the wolf in his loudest voice.", 
"The wolf huffed and he puffed, and he puffed and he huffed, but he could not blow down the brick house.", 
" The big bad wolf was very angry. He looked at the house and saw the chimney.", 
"As quick as a flash, he climbed up on to the roof and into the chimney.", 
"But the big bad wolf was in for a BIG surprise!", 
"The third little pig had been making soup and there was a big pot of boiling soup on the fire.", 
"The wolf slid down the chimney and landed right in it...", 
" ...SPLASH!", 
" With a loud howl, the foolish wolf jumped out of the pot, ran out of the house, and off down the road!", 
"The three little pigs cheered loudly.", 
"The big bad wolf was never seen again, and the three little pigs lived happily ever after!"]

const goldilocks = ["Once upon a time lived Goldilocks and The Three Bears.", 
"One day, Goldilocks went for a walk in the forest and found a house.", 
"She knocked, and when nobody answered, she decided to go inside.", 
"At the table, there were three bowls of porridge. Goldilocks was hungry.", 
"She tasted the porridge from the large bowl. 'This porridge is too salty!' she said.", 
"She tasted the porridge from the medium sized bowl. 'This porridge is too sweet!' she said.", 
"She tasted the porridge from the small bowl. 'This porridge is just right,' she said and she ate it all up.", 
"Goldilocks felt tired, so she walked into the living room and saw three chairs.", 
"She sat in the large chair to rest her feet. 'This chair is too big!' she said.", 
"She sat in the medium sized chair. 'This chair is too big, too!' she said.", 
"She sat in the small chair. 'This chair is just right,' she sighed.", 
"Just as Goldilocks settled down into the chair to rest, it broke into pieces!", 
"By now, Goldilocks was very tired, so she went upstairs to the bedroom.", 
"She lay down on the large bed. 'This bed is too hard!' she said.", 
"She lay down on the medium sized bed. 'This bed is too soft!' she said.", 
"She lay down on the small bed. 'This bed is just right,' she sighed. She curled up and fell asleep.", 
"As she was sleeping, The Three Bears came home.", 
"'Someone’s been eating my porridge,' growled Daddy Bear.", 
"'Someone’s been eating my porridge,' said Mummy Bear.", 
"'Someone’s been eating my porridge and it’s all gone!' cried Baby Bear.", 
"'Someone’s been sitting in my chair! growled Daddy Bear.", 
"'Someone’s been sitting in my chair!' said Mummy Bear.", 
"'Someone’s been sitting in my chair and it’s broken!' cried Baby Bear.", 
"When they got upstairs to the bedroom, Daddy Bear growled, 'Someone’s been sleeping on my bed.'", 
"'Someone’s been sleeping on my bed too,' said the Mummy Bear", 
"'Someone’s been sleeping in my bed, and she’s still there!' cried Baby Bear.", 
"Just then Goldilocks woke up and saw The Three Bears. 'Help!' she screamed.", 
"Goldilocks ran down the stairs and into the forest. And she never went back into the woods again."]

function randomString(book){
    let result = " ";
    for (let i = 0; i < book.length; i++) {
        random = (Math.floor(Math.random() * book.length));
        result = book[random];
    }
    return result;
}
console.log(`Your random text is: ${randomString(threePigs)} ${randomString(redRidingHood)} ${randomString(goldilocks)}`)




